INSERT INTO dbo.Categoria VALUES (1, 'RPG')
INSERT INTO dbo.Categoria VALUES (2, 'Corrida')
INSERT INTO dbo.Categoria VALUES (3, 'Aventura')
INSERT INTO dbo.Categoria VALUES (4, 'Luta')
INSERT INTO dbo.Categoria VALUES (5, 'Esporte')

INSERT INTO Selo VALUES (1, 'Ouro')
INSERT INTO Selo VALUES (2, 'Prata')
INSERT INTO Selo VALUES (3, 'Bronze')

INSERT INTO dbo.Jogo VALUES ('Chrono Trigger',60,'No message',3,null,null,1, null)
INSERT INTO dbo.Jogo VALUES ('Top Gear',20, 'No message',3,null,null,2, null)
INSERT INTO dbo.Jogo VALUES ('Megaman X',40, 'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Super Metroid',35, 'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Donkey Kong Country',25, 'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Super Mario Kart',40, 'No message',3,null,null,2, null)
INSERT INTO dbo.Jogo VALUES ('Super Street Fighter',25, 'No message',3,null,null,4, null)
INSERT INTO dbo.Jogo VALUES ('Mortal Kombat 2',37,'No message',3,null,null,4, null)
INSERT INTO dbo.Jogo VALUES ('Killer Instinct',18,'No message',3,null,null,4, null)
INSERT INTO dbo.Jogo VALUES ('Final Fight',12,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Super Mario 1',70,'No message',3,null,null,1, null)
INSERT INTO dbo.Jogo VALUES ('Aladdin',16,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Rock ''n Roll Racing',22,'No message',3,null,null,2, null)
INSERT INTO dbo.Jogo VALUES ('Zelda: A link to the past',110,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Final Fantasy VI',30.5,'No message',3,null,null,1, null)
INSERT INTO dbo.Jogo VALUES ('International Super Star Soccer Deluxe',45,'No message',3,null,null,5, null)
INSERT INTO dbo.Jogo VALUES ('Contra III',28,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Sunset Riders',37.9,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Goof Troop',41.9,'No message',3,null,null,3, null)
INSERT INTO dbo.Jogo VALUES ('Mickey to Donald: Magical Adventure 3',32.9,'No message',3,null,null,3, null)